-- MySQL Script generated by MySQL Workbench
-- Tue Sep  3 02:11:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema corporativo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema corporativo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `corporativo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `corporativo` ;

-- -----------------------------------------------------
-- Table `corporativo`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corporativo`.`states` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corporativo`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corporativo`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `state_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cities_ states_idx` (`state_id` ASC) VISIBLE,
  CONSTRAINT `fk_cities_ states`
    FOREIGN KEY (`state_id`)
    REFERENCES `corporativo`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corporativo`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corporativo`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `zip_code` VARCHAR(9) NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  `number` VARCHAR(45) NULL,
  `complement` VARCHAR(255) NULL,
  `neighborhood` VARCHAR(255) NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_addresses_cities1_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_addresses_cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `corporativo`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corporativo`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corporativo`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `register` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `password` VARCHAR(255) NOT NULL,
  `role` INT NOT NULL DEFAULT 0,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `register_UNIQUE` (`register` ASC) VISIBLE,
  INDEX `fk_employees_addresses1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_addresses1`
    FOREIGN KEY (`address_id`)
    REFERENCES `corporativo`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corporativo`.`pilots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corporativo`.`pilots` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `birth_date` DATE NOT NULL,
  `brevet` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `brevet_UNIQUE` (`brevet` ASC) VISIBLE,
  INDEX `fk_pilots_addresses1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_pilots_addresses1`
    FOREIGN KEY (`address_id`)
    REFERENCES `corporativo`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corporativo`.`airports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corporativo`.`airports` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_airports_cities1_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_airports_cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `corporativo`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corporativo`.`flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corporativo`.`flights` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `departure_time` TIMESTAMP NOT NULL,
  `arrival_time` TIMESTAMP NOT NULL,
  `economic_value` FLOAT NOT NULL,
  `first_class_value` FLOAT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `airport_id` INT NOT NULL,
  `pilot_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_flights_airports1_idx` (`airport_id` ASC) VISIBLE,
  INDEX `fk_flights_pilots1_idx` (`pilot_id` ASC) VISIBLE,
  CONSTRAINT `fk_flights_airports1`
    FOREIGN KEY (`airport_id`)
    REFERENCES `corporativo`.`airports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flights_pilots1`
    FOREIGN KEY (`pilot_id`)
    REFERENCES `corporativo`.`pilots` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corporativo`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corporativo`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT NOW(),
  `approved` TINYINT NOT NULL DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 1,
  `flight_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_flights1_idx` (`flight_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_flights1`
    FOREIGN KEY (`flight_id`)
    REFERENCES `corporativo`.`flights` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `corporativo`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corporativo`.`tickets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `seat` VARCHAR(3) NOT NULL,
  `value` FLOAT NOT NULL,
  `check_in` TIMESTAMP NULL DEFAULT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tickets_orders1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_tickets_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `corporativo`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
